baseURL = 'darikletter.de'
languageCode = 'de-de'
title = "Darius's garden"
theme = 'daris-theme'
sectionPagesMenu = 'main'

[params]
  author = 'Darius Kletter'
  description = "My garden planted with thoughts and knowledge."
  DateForm = "Jan 2, 2006"
