baseURL = 'darikletter.de'
languageCode = 'en-us'
title = "Darius's garden"
theme = 'daris-theme'
sectionPagesMenu = 'main'

[params]
  author = 'Darius Kletter'
  description = "My garden planted with thoughts and knowledge."
